name: Richard Mulholland
favicon: null
layout_spectrum: 0.7356867131311446
typography_spectrum: 0.02919291495345533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5951553855556995
  lightness: 0.2536891088820994
  saturation: 0.6124950326047838
  rhythmicContrast: 0.06017497251741588
purpose: []
